
                                            <!-- MacBook layer-->
                                            <div class="tp-caption tp-resizeme rs-parallaxlevel-1" id="slide-235-layer-1" data-x="['right','right','center','center']" data-hoffset="['50','-453','70','60']" data-y="['middle','middle','middle','bottom']" data-voffset="['80','50','211','25']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="x:right;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" data-start="2500" data-responsive_offset="on" style="z-index: 9;"><img src="images/macbookpro.png" alt="" width="1000" height="600" data-ww="['1000px','1000px','500px','350px']" data-hh="['600px','600px','300px','210px']" data-no-retina>
                                            </div>
    
                                            <!-- Macbook screenshot  -->
                                            <div class="tp-caption tp-resizeme rs-parallaxlevel-1" id="slide-235-layer-2" data-x="['left','left','center','center']" data-hoffset="['523','865','70','60']" data-y="['top','top','top','bottom']" data-voffset="['246','216','580','63']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="z:0;rX:0deg;rY:0;rZ:0;sX:1.5;sY:1.5;skX:0;skY:0;opacity:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="3350" data-responsive_offset="on" style="z-index: 10;"><img src="images/screenshot_pc.png" alt="" width="653" height="408" data-ww="['653px','653px','330px','230px']" data-hh="['408px','408px','206px','144px']" data-no-retina>
                                            </div>
    
                                            <!-- Ipad Layer -->
                                            <div class="tp-caption tp-resizeme rs-parallaxlevel-2" id="slide-235-layer-3" data-x="['left','left','center','center']" data-hoffset="['950','633','-110','-60']" data-y="['top','top','top','bottom']" data-voffset="['100','203','590','20']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="x:right;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" data-start="2750" data-responsive_offset="on" style="z-index: 7;"><img src="images/ipad_dark.png" alt="" width="430" height="540" data-ww="['430px','430px','200px','170px']" data-hh="['540px','540px','251px','213px']" data-no-retina>
                                            </div>
    
                                            <!-- ipad screenshot 70-->
                                            <div class="tp-caption tp-resizeme rs-parallaxlevel-2" id="slide-235-layer-4" data-x="['left','left','left','center']" data-hoffset="['1020','703','212','-60']" data-y="['top','top','top','bottom']" data-voffset="['188','291','632','50']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="z:0;rX:0deg;rY:0;rZ:0;sX:1.5;sY:1.5;skX:0;skY:0;opacity:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="3700" data-responsive_offset="on" style="z-index: 8;"><img src="images/screenshot-ipad.png" alt="" width="290" height="374" data-ww="['290px','290px','135px','115px']" data-hh="['374px','374px','174px','148px']" data-no-retina>
                                            </div>
    
                                            <!-- iphone layer 63-->
                                            <div class="tp-caption tp-resizeme rs-parallaxlevel-3" id="slide-235-layer-5" data-x="['left','left','left','left']" data-hoffset="['1230','553','127','58']" data-y="['top','top','top','top']" data-voffset="['297','297','622','529']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="x:right;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" data-start="3000" data-responsive_offset="on" style="z-index: 9;"><img src="images/ihpone_dark.png" alt="" width="260" height="450" data-ww="['260px','260px','130px','100px']" data-hh="['450px','450px','225px','173px']" data-no-retina>
                                            </div>
    
                                            <!-- iphone screenshot 45-->
                                            <div class="tp-caption tp-resizeme rs-parallaxlevel-3" id="slide-235-layer-6" data-x="['left','left','left','left']" data-hoffset="['1275','598','150','75']" data-y="['top','top','top','top']" data-voffset="['380','379','663','560']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="z:0;rX:0deg;rY:0;rZ:0;sX:1.5;sY:1.5;skX:0;skY:0;opacity:0;s:1500;e:Power3.easeOut;" data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="3950" data-responsive_offset="on" style="z-index: 10;"><img src="images/screenshot-phone.png" alt="" width="170" height="286" data-ww="['170px','170px','85px','66px']" data-hh="['286px','286px','143px','111px']" data-no-retina>
                                            </div>
    
                                            <!-- Title layer -->
                                            <div class="tp-caption WebProduct-Title-Light tp-resizeme rs-parallaxlevel-0" id="slide-235-layer-7" data-x="['left','left','left','left']" data-hoffset="['30','30','200','80']" data-y="['middle','middle','top','top']" data-voffset="['-110','-110','137','130']" data-fontsize="['90','90','75','75']" data-lineheight="['90','90','75','70']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="x:-50px;opacity:0;s:1000;e:Power2.easeOut;" data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 11; white-space: nowrap;">NUS
                                                <br>
                                                Capulator
                                            </div>